### ISSUE TITLE
week 01 作業回饋

### ISSUE THREAD

**Issue by azole** [pj-99/git-practice#1]
整體做得很好且深入，看得出來用心。

一個小地方確認一下，你寫到:
> git hash-object 也可以直接讀某個檔案的內容：
<img width="472" alt="image" src="https://github.com/user-attachments/assets/cbf5e7a6-162c-4266-bed0-13cd07f4045f">

但根據你實驗的結果，`hash-object` 看起來不像直接讀某個檔案的內容，而是在計算指定檔案的 sha-1 值？

**Comment by pj-99** [comment]
謝謝小賴老師的回饋，確實原本的描述不準確，修改了一下，感謝老師

**Comment by azole** [comment]
ok 很好，可以 close 了
